# Generated by Django 2.2.3 on 2019-07-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_assignment',
                'ordering': ['user', 'item_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthItem',
            fields=[
                ('type', models.SmallIntegerField()),
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('data', models.BinaryField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_item',
                'ordering': ['type', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthItemChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_item_child',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthRule',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('data', models.BinaryField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_rule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserYii',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('access_token', models.TextField(blank=True, null=True)),
                ('countries', models.TextField(blank=True, null=True)),
                ('projects', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user_yii',
                'managed': False,
            },
        ),
    ]
