# Generated by Django 2.2.3 on 2019-07-25 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0002_auto_20190725_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='authassignment',
            name='item_name',
            field=models.ForeignKey(db_column='item_name', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='legacy.AuthItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authassignment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='legacy.AuthUserYii'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='authassignment',
            unique_together={('item_name', 'user')},
        ),
    ]
