# Generated by Django 2.2.3 on 2019-07-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0003_auto_20190725_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authassignment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
