# Generated by Django 2.2.3 on 2019-07-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0004_auto_20190725_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authassignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='authassignment',
            unique_together=set(),
        ),
    ]
