# Generated by Django 2.2.3 on 2019-07-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0005_auto_20190725_1855'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authassignment',
            unique_together={('item_name', 'user')},
        ),
    ]
