# Generated by Django 2.2.3 on 2019-07-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0006_auto_20190725_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authitemchild',
            options={},
        ),
    ]
