# Generated by Django 2.2.3 on 2019-07-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0007_auto_20190725_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='authitemchild',
            name='child',
            field=models.ForeignKey(db_column='child', default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child', to='legacy.AuthItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authitemchild',
            name='parent',
            field=models.ForeignKey(db_column='parent', default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent', to='legacy.AuthItem'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='authitemchild',
            unique_together={('parent', 'child')},
        ),
    ]
