# Generated by Django 2.2.3 on 2019-07-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0010_auto_20190725_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authitem',
            options={'ordering': ['type', 'name']},
        ),
    ]
