# Generated by Django 2.2.3 on 2019-07-25 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0011_auto_20190725_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authrule',
            options={},
        ),
        migrations.AddField(
            model_name='authitem',
            name='rule_name',
            field=models.ForeignKey(blank=True, db_column='rule_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='legacy.AuthRule'),
        ),
        migrations.AlterField(
            model_name='authitem',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authitem',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
