# Generated by Django 2.2.3 on 2019-07-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0013_auto_20190725_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuseryii',
            options={},
        ),
    ]
