# Generated by Django 2.2.3 on 2019-07-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0014_auto_20190725_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuseryii',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
