# Generated by Django 2.2.3 on 2019-07-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('document', models.CharField(blank=True, max_length=45, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('country', models.CharField(blank=True, max_length=45, null=True)),
                ('community', models.CharField(blank=True, max_length=255, null=True)),
                ('org_id', models.IntegerField(blank=True, null=True)),
                ('phone_personal', models.CharField(blank=True, max_length=45, null=True)),
                ('type_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['event', 'contact'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('first_name', models.CharField(blank=True, max_length=80, null=True)),
                ('document', models.CharField(blank=True, max_length=40, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('community', models.CharField(blank=True, max_length=40, null=True)),
                ('municipality', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('education_id', models.IntegerField(blank=True, null=True)),
                ('phone_personal', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_work', models.CharField(blank=True, max_length=20, null=True)),
                ('men_home', models.IntegerField(blank=True, null=True)),
                ('women_home', models.IntegerField(blank=True, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contact',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountryAux',
            fields=[
                ('pais_en_espaniol', models.CharField(max_length=255)),
                ('pais_en_ingles', models.CharField(max_length=255)),
                ('codigo_numerico', models.IntegerField()),
                ('alfa2', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('alfa3', models.CharField(max_length=3)),
                ('coordenada_x', models.CharField(max_length=255)),
                ('coordenada_y', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'country_aux',
                'ordering': ['pais_en_ingles'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=45, null=True)),
                ('list_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_list',
                'ordering': ['list_id', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('structure_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=455)),
                ('title', models.TextField(blank=True, null=True)),
                ('implementing_organization_id', models.IntegerField()),
                ('organizer', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('country_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('filter_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'filter',
                'ordering': ['slug', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('organization_type_id', models.IntegerField(blank=True, null=True)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('country_id', models.IntegerField(blank=True, null=True)),
                ('is_implementer', models.BooleanField()),
            ],
            options={
                'db_table': 'organization',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organization_type',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('code', models.CharField(max_length=255)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('colors', models.TextField()),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('goal_men', models.IntegerField(blank=True, null=True)),
                ('goal_women', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('development_area', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('productive_area', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('age_development_plantation', models.IntegerField(blank=True, null=True)),
                ('age_productive_plantation', models.IntegerField(blank=True, null=True)),
                ('yield_field', models.FloatField(blank=True, db_column='yield', null=True)),
                ('date_entry_project', models.DateField(blank=True, null=True)),
                ('date_end_project', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_contact',
                'ordering': ['project', 'contact'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
                ('structure_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'structure',
                'ordering': ['project', 'description'],
                'managed': False,
            },
        ),
    ]
