# Generated by Django 2.2.3 on 2019-07-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name_es', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('codigo_numerico', models.IntegerField()),
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('alfa3', models.CharField(max_length=3)),
                ('x', models.CharField(max_length=255)),
                ('y', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'country',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='CountryAux',
        ),
    ]
