# Generated by Django 2.2.3 on 2019-07-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20190729_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name']},
        ),
    ]
