# Generated by Django 2.2.6 on 2019-10-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20191025_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.CharField(blank=True, max_length=64, null=True, verbose_name='User')),
                ('module', models.CharField(blank=True, max_length=64, null=True, verbose_name='Module')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='created_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='updated_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='created_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='updated_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by'),
        ),
    ]
