# Generated by Django 2.2.3 on 2019-07-29 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20190729_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Country'),
        ),
    ]
