# Generated by Django 2.2.6 on 2019-10-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_projectcontact_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actualimen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual Indirect Men'),
        ),
        migrations.AddField(
            model_name='project',
            name='actualiwomen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual Indirect Women'),
        ),
        migrations.AddField(
            model_name='project',
            name='actualmen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual Direct Men'),
        ),
        migrations.AddField(
            model_name='project',
            name='actualwomen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual Direct Women'),
        ),
    ]
