# Generated by Django 2.2.3 on 2019-07-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20190729_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
    ]
