# Generated by Django 2.2.3 on 2019-07-29 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_auto_20190729_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='country_id',
            new_name='country_number',
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Country'),
        ),
    ]
