# Generated by Django 2.2.3 on 2019-07-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_auto_20190729_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['event', 'contact']},
        ),
    ]
