# Generated by Django 2.2.3 on 2019-07-29 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_auto_20190729_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
