# Generated by Django 2.2.6 on 2019-11-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_auto_20191101_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='salesforce',
            field=models.CharField(blank=True, max_length=255, null=True,
                                   unique=True, verbose_name='Salesforce Id'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='monitoring.ContactType', verbose_name='Contact Type'),
        ),
    ]
