# Generated by Django 2.2.3 on 2019-07-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_auto_20190729_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='contact',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Event'),
            preserve_default=False,
        ),
    ]
