# Generated by Django 2.2.3 on 2019-07-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_auto_20190729_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['project', 'description']},
        ),
    ]
