# Generated by Django 2.2.3 on 2019-07-29 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_auto_20190729_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='structure_id',
        ),
        migrations.AddField(
            model_name='structure',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='monitoring.Structure'),
        ),
    ]
