# Generated by Django 2.2.3 on 2019-07-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_auto_20190729_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Project'),
            preserve_default=False,
        ),
    ]
