# Generated by Django 2.2.6 on 2019-11-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_auto_20191107_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='varname',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Acronym'),
        ),
    ]
