# Generated by Django 2.2.6 on 2019-11-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_auto_20191107_0756'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectcontact',
            unique_together=set(),
        ),
    ]
