# Generated by Django 2.2.3 on 2019-07-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_structure_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcontact',
            options={'ordering': ['project', 'contact']},
        ),
    ]
