# Generated by Django 2.2.3 on 2019-07-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_auto_20190729_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontact',
            name='contact',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Project'),
            preserve_default=False,
        ),
    ]
