# Generated by Django 2.2.6 on 2019-11-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_auto_20191107_0817'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectcontact',
            unique_together={('project', 'contact')},
        ),
    ]
