# Generated by Django 2.2.6 on 2019-11-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_auto_20191107_0837'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
    ]
