# Generated by Django 2.2.3 on 2019-07-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_auto_20190729_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcontact',
            options={'ordering': ['project']},
        ),
    ]
