# Generated by Django 2.2.6 on 2019-11-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_auto_20191107_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontact',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='monitoring.Organization', verbose_name='Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoring.Project', verbose_name='Project'),
        ),
    ]
