# Generated by Django 2.2.8 on 2019-12-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_beneficiaries'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='beneficiaries',
            table='beneficiaries',
        ),
    ]
