# Generated by Django 2.2.8 on 2019-12-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_auto_20191212_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='atype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Type'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='atype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SubProject Type'),
        ),
    ]
