# Generated by Django 2.2.8 on 2019-12-12 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0020_auto_20191212_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='lwrregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.LWRRegion', verbose_name='LWR Region'),
        ),
    ]
