# Generated by Django 2.2.3 on 2019-07-29 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0020_auto_20190729_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='filter_id',
        ),
        migrations.AddField(
            model_name='filter',
            name='filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='monitoring.Filter'),
        ),
    ]
