# Generated by Django 2.2.8 on 2019-12-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_subproject_lwrregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Owner'),
        ),
    ]
