# Generated by Django 2.2.3 on 2019-07-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_auto_20190729_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name']},
        ),
    ]
