# Generated by Django 2.2.8 on 2019-12-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='agriculture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subproject',
            name='agriculture_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subproject',
            name='climatechange_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subproject',
            name='eoperations_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
