# Generated by Django 2.2.3 on 2019-07-29 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_auto_20190729_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='country_id',
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Country'),
        ),
    ]
