# Generated by Django 2.2.8 on 2020-01-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0023_auto_20191212_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontact',
            name='subproject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.SubProject', verbose_name='SubProject'),
        ),
    ]
