# Generated by Django 2.2.3 on 2019-07-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0023_auto_20190729_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datalist',
            options={'ordering': ['id', 'name']},
        ),
    ]
