# Generated by Django 2.2.3 on 2019-07-29 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_auto_20190729_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='list_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.DataList'),
        ),
    ]
