# Generated by Django 2.2.8 on 2020-01-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_projectcontact_subproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontact',
            name='subproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.SubProject', verbose_name='SubProject'),
        ),
    ]
