# Generated by Django 2.2.9 on 2020-01-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0025_auto_20200109_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='lwrregion',
            name='name_es',
            field=models.CharField(default='', max_length=20, verbose_name='Name ES'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lwrregion',
            name='name_fr',
            field=models.CharField(default='', max_length=20, verbose_name='Name FR'),
            preserve_default=False,
        ),
    ]
