# Generated by Django 2.2.3 on 2019-07-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0025_auto_20190729_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_es', models.CharField(max_length=100)),
                ('name_fr', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        #migrations.RenameField(
        #    model_name='datalist',
        #    old_name='list_id',
        #    new_name='data_list',
        #),
    ]
