# Generated by Django 2.2.3 on 2019-07-31 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0026_auto_20190731_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datalist',
            old_name='list_id',
            new_name='data_list',
        ),
    ]
