# Generated by Django 2.2.3 on 2019-07-31 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0027_auto_20190731_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='education_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Education'),
        ),
    ]
