# Generated by Django 2.2.3 on 2019-07-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0030_auto_20190731_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='type_id',
            new_name='type',
        ),
    ]
