# Generated by Django 2.2.3 on 2019-07-31 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0032_auto_20190731_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontact',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Product'),
        ),
    ]
