# Generated by Django 2.2.3 on 2019-08-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0033_auto_20190731_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.ContactType'),
        ),
    ]
