# Generated by Django 2.2.3 on 2019-08-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0034_auto_20190801_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='type_id',
            new_name='type',
        ),
    ]
