# Generated by Django 2.2.3 on 2019-08-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0035_auto_20190801_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='org_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
