# Generated by Django 2.2.3 on 2019-08-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0037_auto_20190801_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
