# Generated by Django 2.2.3 on 2019-08-01 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0038_auto_20190801_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='implementing_organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Organization'),
        ),
    ]
