# Generated by Django 2.2.3 on 2019-08-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0041_auto_20190812_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organization_type_id',
            new_name='organization_type',
        ),
    ]
