# Generated by Django 2.2.3 on 2019-08-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0042_auto_20190812_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='structure_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Structure'),
        ),
    ]
