# Generated by Django 2.2.3 on 2019-08-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0043_auto_20190812_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='structure_id',
            new_name='structure',
        ),
    ]
