# Generated by Django 2.2.4 on 2019-08-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0045_auto_20190815_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
