# Generated by Django 2.2.4 on 2019-08-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0046_auto_20190815_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='goal_men',
            new_name='goalmen',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='goal_women',
            new_name='goalwomen',
        ),
        migrations.AlterField(
            model_name='project',
            name='goalmen',
            field=models.IntegerField(blank=True, db_column='goal_men', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='goalwomen',
            field=models.IntegerField(blank=True, db_column='goal_women', null=True),
        ),
    ]
