# Generated by Django 2.2.4 on 2019-08-20 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0048_auto_20190820_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Region'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='countries',
            field=models.ManyToManyField(blank=True, null=True, to='monitoring.Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='monitoring.Project'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='regiones',
            field=models.ManyToManyField(blank=True, null=True, to='monitoring.Region'),
        ),
    ]
