# Generated by Django 2.2.4 on 2019-08-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0049_auto_20190820_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='countries',
            field=models.ManyToManyField(blank=True, to='monitoring.Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(blank=True, to='monitoring.Project'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='regiones',
            field=models.ManyToManyField(blank=True, to='monitoring.Region'),
        ),
    ]
