# Generated by Django 2.2.4 on 2019-08-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0050_auto_20190820_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='colors',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
