# Generated by Django 2.2.4 on 2019-09-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0056_auto_20190908_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_fr',
            field=models.CharField(default='', max_length=255, verbose_name='Name_FR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='phonecode',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Phone Code'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='name_es',
            field=models.CharField(max_length=100, verbose_name='Name ES'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='name_fr',
            field=models.CharField(max_length=100, verbose_name='Name FR'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_es',
            field=models.CharField(max_length=255, verbose_name='Name_ES'),
        ),
        migrations.AlterField(
            model_name='education',
            name='name_es',
            field=models.CharField(max_length=100, verbose_name='Name ES'),
        ),
        migrations.AlterField(
            model_name='education',
            name='name_fr',
            field=models.CharField(max_length=100, verbose_name='Name FR'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='name_es',
            field=models.CharField(max_length=255, verbose_name='Name ES'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='name_fr',
            field=models.CharField(max_length=255, verbose_name='Name FR'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_es',
            field=models.CharField(max_length=100, verbose_name='Name ES'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_fr',
            field=models.CharField(max_length=100, verbose_name='Name FR'),
        ),
    ]
