# Generated by Django 2.2.4 on 2019-09-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0057_auto_20190908_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phonecode',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Phone Code'),
        ),
    ]
