# Generated by Django 2.2.4 on 2019-09-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0058_auto_20190908_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='subregions',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subregions'),
        ),
    ]
