# Generated by Django 2.2.4 on 2019-09-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0060_auto_20190909_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='salesforce',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Salesforce Id'),
        ),
    ]
