# Generated by Django 2.2.4 on 2019-09-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0063_auto_20190909_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='regions',
            new_name='lwrregions',
        ),
    ]
