# Generated by Django 2.2.4 on 2019-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0064_auto_20190909_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region'),
        ),
    ]
