# Generated by Django 2.2.4 on 2019-09-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0065_auto_20190909_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='targetimen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Target Indirect Men'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='targetiwomen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Target Indirect Women'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='targetmen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Target Men'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='targetwomen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Target Women'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_es',
            field=models.CharField(max_length=255, verbose_name='Name ES'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_fr',
            field=models.CharField(max_length=255, verbose_name='Name FR'),
        ),
    ]
