# Generated by Django 2.2.4 on 2019-09-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0066_auto_20190909_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='goalmen',
        ),
        migrations.RemoveField(
            model_name='project',
            name='goalwomen',
        ),
        migrations.AddField(
            model_name='project',
            name='targetmen',
            field=models.IntegerField(blank=True, db_column='goal_men', null=True, verbose_name='Target Men'),
        ),
        migrations.AddField(
            model_name='project',
            name='targetwomen',
            field=models.IntegerField(blank=True, db_column='goal_women', null=True, verbose_name='Target Women'),
        ),
    ]
