# Generated by Django 2.2.4 on 2019-09-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0067_auto_20190909_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lwrregion',
            name='id',
        ),
        migrations.AddField(
            model_name='lwrregion',
            name='code',
            field=models.CharField(default='', max_length=8, serialize=False, verbose_name='Id'),
            preserve_default=False,
        ),
    ]
