# Generated by Django 2.2.4 on 2019-09-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0068_auto_20190909_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lwrregion',
            name='code',
            field=models.CharField(max_length=8, verbose_name='Id'),
        ),
    ]
