# Generated by Django 2.2.4 on 2019-09-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0071_auto_20190909_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='lwrregion',
        ),
    ]
