# Generated by Django 2.2.4 on 2019-09-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0073_country_lwrregion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lwrregions',
        ),
    ]
