# Generated by Django 2.2.4 on 2019-09-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0075_profile_lwrregions'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lwrregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.LWRRegion', verbose_name='LWR Region'),
        ),
    ]
