# Generated by Django 2.2.4 on 2019-09-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0076_project_lwrregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('In Development', 'In Development'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Closed', 'Closed'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='status',
            field=models.CharField(blank=True, choices=[('Proposed', 'Proposed'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated'), ('Closed', 'Closed')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
