# Generated by Django 2.2.4 on 2019-09-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0077_auto_20190911_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='End'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Start'),
        ),
    ]
