# Generated by Django 2.2.4 on 2019-09-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0078_auto_20190911_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='targetimen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Target Indirect Men'),
        ),
        migrations.AddField(
            model_name='project',
            name='targetiwomen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Target Indirect Women'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='targetmen',
            field=models.IntegerField(blank=True, db_column='goal_men', null=True, verbose_name='Target Direct Men'),
        ),
        migrations.AlterField(
            model_name='project',
            name='targetwomen',
            field=models.IntegerField(blank=True, db_column='goal_women', null=True, verbose_name='Target Direct Women'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='targetmen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Target Direct Men'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='targetwomen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Target Direct Women'),
        ),
    ]
