# Generated by Django 2.2.4 on 2019-09-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0079_auto_20190913_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='salesforce',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Salesforce Id'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='salesforce',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Salesforce Id'),
        ),
    ]
