# Generated by Django 2.2.4 on 2019-09-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0081_auto_20190913_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='recordtype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Record Type'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='recordtype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Record Type'),
        ),
    ]
