# Generated by Django 2.2.4 on 2019-09-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0082_auto_20190913_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Code'),
        ),
    ]
