# Generated by Django 2.2.4 on 2019-09-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0083_auto_20190913_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='country',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='event',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='project',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='structure',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Structure',
        ),
    ]
