# Generated by Django 2.2.4 on 2019-09-17 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0084_auto_20190917_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Organization', verbose_name='Organization'),
        ),
    ]
