# Generated by Django 2.2.4 on 2019-09-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0085_projectcontact_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='end',
            field=models.IntegerField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='start',
            field=models.IntegerField(verbose_name='Start'),
        ),
    ]
