# Generated by Django 2.2.4 on 2019-09-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0087_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='file_es',
            field=models.FileField(default='', upload_to='templates/', verbose_name='File ES'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='file_fr',
            field=models.FileField(default='', upload_to='templates/', verbose_name='File FR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='name_es',
            field=models.CharField(default='', max_length=20, verbose_name='Name ES'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='name_fr',
            field=models.CharField(default='', max_length=20, verbose_name='Name FR'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Filename'),
        ),
    ]
