# Generated by Django 2.2.4 on 2019-09-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0088_auto_20190918_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name_es',
            field=models.CharField(max_length=50, verbose_name='Name ES'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name_fr',
            field=models.CharField(max_length=50, verbose_name='Name FR'),
        ),
    ]
