# Generated by Django 2.2.4 on 2019-09-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0089_auto_20190918_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_es', models.CharField(max_length=255, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Sex',
                'verbose_name_plural': 'Sex',
                'ordering': ['id'],
            },
        ),
    ]
