# Generated by Django 2.2.4 on 2019-09-25 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0090_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Sex', verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='name_es',
            field=models.CharField(max_length=255, verbose_name='Name ES'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='name_fr',
            field=models.CharField(max_length=255, verbose_name='Name FR'),
        ),
    ]
