# Generated by Django 2.2.4 on 2019-10-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0092_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='actualimen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual Indirect Men'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='actualiwomen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual Indirect Women'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='actualmen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual Direct Men'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='actualwomen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual Direct Women'),
        ),
    ]
