# Generated by Django 2.2.4 on 2019-10-02 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0094_subproject_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='modified',
        ),
        migrations.AddField(
            model_name='contact',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subproject',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
    ]
