# Generated by Django 2.2.4 on 2019-10-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0095_auto_20191002_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
