# Generated by Django 2.2.4 on 2019-10-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0096_auto_20191007_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_implementer',
            field=models.BooleanField(default=False, verbose_name='Is Implementer'),
        ),
    ]
