# Generated by Django 2.2.4 on 2019-10-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0100_auto_20191011_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='varname',
            field=models.CharField(default='', max_length=100, verbose_name='Variable Id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='varname_es',
            field=models.CharField(default='', max_length=100, verbose_name='Variable Id ES'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='varname_fr',
            field=models.CharField(default='', max_length=100, verbose_name='Variable Id FR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sex',
            name='varname',
            field=models.CharField(default='', max_length=255, verbose_name='Variable Id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sex',
            name='varname_es',
            field=models.CharField(default='', max_length=255, verbose_name='Variable Id ES'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sex',
            name='varname_fr',
            field=models.CharField(default='', max_length=255, verbose_name='Variable Id FR'),
            preserve_default=False,
        ),
    ]
