# Generated by Django 2.2.4 on 2019-10-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0102_auto_20191014_1752'),
    ]

    operations = [
    ]
