# Generated by Django 2.2.4 on 2019-10-14 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0103_remove_contact_created_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Source', verbose_name='Data Source'),
        ),
        migrations.AddField(
            model_name='organization',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Source', verbose_name='Data Source'),
        ),
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Source', verbose_name='Data Source'),
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Source', verbose_name='Data Source'),
        ),
        migrations.AddField(
            model_name='request',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Source', verbose_name='Data Source'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Source', verbose_name='Data Source'),
        ),
    ]
