# Generated by Django 2.2.4 on 2019-10-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0104_auto_20191014_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.CharField(max_length=16, primary_key=True,
                                   serialize=False, verbose_name='Id'),
        ),
    ]
