# Generated by Django 2.2.4 on 2019-10-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0105_auto_20191014_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='altitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Altitude'),
        ),
        migrations.AddField(
            model_name='contact',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='contact',
            name='precision',
            field=models.FloatField(blank=True, null=True, verbose_name='Precision'),
        ),
    ]
