# Generated by Django 2.2.4 on 2019-10-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0107_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
    ]
