# Generated by Django 2.2.4 on 2019-10-17 15:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0110_auto_20191017_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryNE',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=255, unique=True, verbose_name='Name ES')),
                ('name_fr', models.CharField(max_length=255, unique=True, verbose_name='Name FR')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'countryne',
                'ordering': ('name',),
            },
        ),
    ]
