# Generated by Django 2.2.4 on 2019-10-17 15:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0113_auto_20191017_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryne',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
