# Generated by Django 2.2.4 on 2019-10-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0115_auto_20191017_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryne',
            name='sov_a3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
