# Generated by Django 2.2.4 on 2019-10-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0117_auto_20191017_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='x',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='country',
            name='y',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Y'),
        ),
    ]
