# Generated by Django 2.2.4 on 2019-10-17 17:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0118_auto_20191017_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='precision',
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name='Location'),
        ),
    ]
