# Generated by Django 2.2.4 on 2019-10-21 04:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0121_auto_20191017_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='mapping',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Mapping'),
        ),
    ]
