# Generated by Django 2.2.4 on 2019-10-21 13:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0122_template_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='mapping_es',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True, verbose_name='Mapping ES'),
        ),
        migrations.AddField(
            model_name='template',
            name='mapping_fr',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True, verbose_name='Mapping FR'),
        ),
    ]
