# Generated by Django 2.2.6 on 2019-10-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0123_auto_20191021_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='templates/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='template',
            name='file_es',
            field=models.FileField(blank=True, null=True, upload_to='templates/', verbose_name='File ES'),
        ),
        migrations.AlterField(
            model_name='template',
            name='file_fr',
            field=models.FileField(blank=True, null=True, upload_to='templates/', verbose_name='File FR'),
        ),
    ]
